//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from calcExpr.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IcalcExprListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public partial class calcExprBaseListener : IcalcExprListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.parse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParse([NotNull] calcExprParser.ParseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.parse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParse([NotNull] calcExprParser.ParseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] calcExprParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] calcExprParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.or_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOr_expr([NotNull] calcExprParser.Or_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.or_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOr_expr([NotNull] calcExprParser.Or_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.or_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOr_body([NotNull] calcExprParser.Or_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.or_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOr_body([NotNull] calcExprParser.Or_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.and_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnd_expr([NotNull] calcExprParser.And_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.and_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnd_expr([NotNull] calcExprParser.And_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.and_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnd_body([NotNull] calcExprParser.And_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.and_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnd_body([NotNull] calcExprParser.And_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.rel_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRel_expr([NotNull] calcExprParser.Rel_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.rel_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRel_expr([NotNull] calcExprParser.Rel_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.eq_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEq_expr([NotNull] calcExprParser.Eq_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.eq_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEq_expr([NotNull] calcExprParser.Eq_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.add_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdd_expr([NotNull] calcExprParser.Add_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.add_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdd_expr([NotNull] calcExprParser.Add_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.add_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdd_body([NotNull] calcExprParser.Add_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.add_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdd_body([NotNull] calcExprParser.Add_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.mult_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMult_expr([NotNull] calcExprParser.Mult_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.mult_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMult_expr([NotNull] calcExprParser.Mult_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.mult_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMult_body([NotNull] calcExprParser.Mult_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.mult_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMult_body([NotNull] calcExprParser.Mult_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.unary_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_expr([NotNull] calcExprParser.Unary_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.unary_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_expr([NotNull] calcExprParser.Unary_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.func"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc([NotNull] calcExprParser.FuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.func"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc([NotNull] calcExprParser.FuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.constNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstNumber([NotNull] calcExprParser.ConstNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.constNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstNumber([NotNull] calcExprParser.ConstNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.constString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstString([NotNull] calcExprParser.ConstStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.constString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstString([NotNull] calcExprParser.ConstStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] calcExprParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] calcExprParser.VariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.nullValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullValue([NotNull] calcExprParser.NullValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.nullValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullValue([NotNull] calcExprParser.NullValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.trueValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrueValue([NotNull] calcExprParser.TrueValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.trueValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrueValue([NotNull] calcExprParser.TrueValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.falseValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFalseValue([NotNull] calcExprParser.FalseValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.falseValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFalseValue([NotNull] calcExprParser.FalseValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.braceExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBraceExpr([NotNull] calcExprParser.BraceExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.braceExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBraceExpr([NotNull] calcExprParser.BraceExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar([NotNull] calcExprParser.VarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.var"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar([NotNull] calcExprParser.VarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.multiExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiExpr([NotNull] calcExprParser.MultiExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.multiExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiExpr([NotNull] calcExprParser.MultiExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.unaryparam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryparam([NotNull] calcExprParser.UnaryparamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.unaryparam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryparam([NotNull] calcExprParser.UnaryparamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.continueParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinueParam([NotNull] calcExprParser.ContinueParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.continueParam"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinueParam([NotNull] calcExprParser.ContinueParamContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
