//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from calcExpr.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="calcExprParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public interface IcalcExprListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.parse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParse([NotNull] calcExprParser.ParseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.parse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParse([NotNull] calcExprParser.ParseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] calcExprParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] calcExprParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.or_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOr_expr([NotNull] calcExprParser.Or_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.or_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOr_expr([NotNull] calcExprParser.Or_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.or_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOr_body([NotNull] calcExprParser.Or_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.or_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOr_body([NotNull] calcExprParser.Or_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.and_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnd_expr([NotNull] calcExprParser.And_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.and_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnd_expr([NotNull] calcExprParser.And_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.and_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnd_body([NotNull] calcExprParser.And_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.and_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnd_body([NotNull] calcExprParser.And_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.rel_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRel_expr([NotNull] calcExprParser.Rel_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.rel_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRel_expr([NotNull] calcExprParser.Rel_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.eq_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEq_expr([NotNull] calcExprParser.Eq_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.eq_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEq_expr([NotNull] calcExprParser.Eq_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.add_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdd_expr([NotNull] calcExprParser.Add_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.add_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdd_expr([NotNull] calcExprParser.Add_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.add_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdd_body([NotNull] calcExprParser.Add_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.add_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdd_body([NotNull] calcExprParser.Add_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.mult_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMult_expr([NotNull] calcExprParser.Mult_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.mult_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMult_expr([NotNull] calcExprParser.Mult_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.mult_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMult_body([NotNull] calcExprParser.Mult_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.mult_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMult_body([NotNull] calcExprParser.Mult_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.unary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary_expr([NotNull] calcExprParser.Unary_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.unary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary_expr([NotNull] calcExprParser.Unary_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>func</c>
	/// labeled alternative in <see cref="calcExprParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc([NotNull] calcExprParser.FuncContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>func</c>
	/// labeled alternative in <see cref="calcExprParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc([NotNull] calcExprParser.FuncContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>constNumber</c>
	/// labeled alternative in <see cref="calcExprParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstNumber([NotNull] calcExprParser.ConstNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>constNumber</c>
	/// labeled alternative in <see cref="calcExprParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstNumber([NotNull] calcExprParser.ConstNumberContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>constString</c>
	/// labeled alternative in <see cref="calcExprParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstString([NotNull] calcExprParser.ConstStringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>constString</c>
	/// labeled alternative in <see cref="calcExprParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstString([NotNull] calcExprParser.ConstStringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>variable</c>
	/// labeled alternative in <see cref="calcExprParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable([NotNull] calcExprParser.VariableContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>variable</c>
	/// labeled alternative in <see cref="calcExprParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable([NotNull] calcExprParser.VariableContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>nullValue</c>
	/// labeled alternative in <see cref="calcExprParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNullValue([NotNull] calcExprParser.NullValueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>nullValue</c>
	/// labeled alternative in <see cref="calcExprParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNullValue([NotNull] calcExprParser.NullValueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>trueValue</c>
	/// labeled alternative in <see cref="calcExprParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrueValue([NotNull] calcExprParser.TrueValueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>trueValue</c>
	/// labeled alternative in <see cref="calcExprParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrueValue([NotNull] calcExprParser.TrueValueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>falseValue</c>
	/// labeled alternative in <see cref="calcExprParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFalseValue([NotNull] calcExprParser.FalseValueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>falseValue</c>
	/// labeled alternative in <see cref="calcExprParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFalseValue([NotNull] calcExprParser.FalseValueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>braceExpr</c>
	/// labeled alternative in <see cref="calcExprParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBraceExpr([NotNull] calcExprParser.BraceExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>braceExpr</c>
	/// labeled alternative in <see cref="calcExprParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBraceExpr([NotNull] calcExprParser.BraceExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar([NotNull] calcExprParser.VarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.var"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar([NotNull] calcExprParser.VarContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>multiExpr</c>
	/// labeled alternative in <see cref="calcExprParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiExpr([NotNull] calcExprParser.MultiExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>multiExpr</c>
	/// labeled alternative in <see cref="calcExprParser.params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiExpr([NotNull] calcExprParser.MultiExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="calcExprParser.unaryparam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryparam([NotNull] calcExprParser.UnaryparamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="calcExprParser.unaryparam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryparam([NotNull] calcExprParser.UnaryparamContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>continueParam</c>
	/// labeled alternative in <see cref="calcExprParser.briefparam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinueParam([NotNull] calcExprParser.ContinueParamContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>continueParam</c>
	/// labeled alternative in <see cref="calcExprParser.briefparam"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinueParam([NotNull] calcExprParser.ContinueParamContext context);
}
